services:
  vault:
    image: hashicorp/vault:1.21
    container_name: hashicorp-vault-plugin-crypto-test
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "file": {
              "path": "/vault/data"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          },
          "plugin_directory": "/vault/plugins",
          "log_level": "debug",
          "disable_mlock": true,
          "api_addr": "http://127.0.0.1:8200"
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - ./build:/vault/plugins:ro
      - ./vault-data:/vault/data
    command: server
