services:
  vault:
    image: hashicorp/vault:1.21
    container_name: hashicorp-vault-plugin-crypto-test
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_LOCAL_CONFIG: |
        {
          "plugin_directory": "/vault/plugins",
          "log_level": "debug"
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - ./build:/vault/plugins:ro
    command: server -dev -dev-plugin-dir=/vault/plugins
